### ISSUE TITLE
Unable to use newer than 18.4.0 version of plugins

### ISSUE THREAD

**Issue by neutrino1911** [nebula-plugins/nebula-publishing-plugin#187]
Gradle Plugins Portal shows that 18.4.0 is the latest version event though the latest release in GitHub is 20.2.0
https://plugins.gradle.org/plugin/nebula.maven-publish

I get this error when I'm trying to use 20.2.0 version in my project:
```
* What went wrong:
Plugin [id: 'nebula.maven-publish', version: '20.2.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'nebula.maven-publish:nebula.maven-publish.gradle.plugin:20.2.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    MavenRepo
```

I see that the plugin itself was published to Maven Central
https://mvnrepository.com/artifact/com.netflix.nebula/nebula-publishing-plugin

But metadata is missing
https://mvnrepository.com/artifact/nebula.maven-publish/nebula.maven-publish.gradle.plugin

**Comment by rpalcolea** [comment]
Hi! as noted in https://github.com/nebula-plugins/nebula-publishing-plugin/releases/tag/v19.0.0, the plugins were relocated from `nebula.<plugin id>` to `com.netflix.nebula.<plugin id>` in order to align with Gradle Plugin portal requirements 

Moving to the new plugin ids should get you unblocked

I went ahead and modified the README.md a bit since it was kind of confusing

**Comment by neutrino1911** [comment]
Hi, Roberto! It's working this way, thank you.
